name: Run Simulation && Publish Results

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        L: [10, 20]
        n: [100, 200, 300]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Ising Model Simulation
      run: |
        python ising_model.py ${{ matrix.L }} ${{ matrix.n }} > results_${{ matrix.python-version }}_L${{ matrix.L }}_n${{ matrix.n }}.txt
    - name: Archive simulation results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          results_${{ matrix.python-version }}_L${{ matrix.L }}_n${{ matrix.n }}.txt
          *.png
  update-gh-pages:
    needs: run-simulation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download simulation results
      uses: actions/download-artifact@v2
      with:
        name: results
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install matplotlib
      run: pip install matplotlib
    - name: Generate plots
      run: python generate_plots.py
    - name: Checkout gh-pages branch
      run: |
        git fetch
        git checkout gh-pages || git checkout --orphan gh-pages
    - name: Generate index.html
      run: python generate_index.py
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html *.png
        git commit -m "Update simulation results" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
