name: Test Simulation for PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        L: [10, 20]
        n: [10000, 20000, 30000]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Ising Model Simulation
      run: |
        python ising_model.py ${{ matrix.L }} ${{ matrix.n }} > results_${{ matrix.python-version }}_L${{ matrix.L }}_n${{ matrix.n }}.txt
    - name: Generate Plots
      run: python generate_plots.py
